Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,11 +32,12 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     services:
-      mssql:
-        image: mcr.microsoft.com/mssql/server:2022-latest
+      sql-edge:
+        image: mcr.microsoft.com/azure-sql-edge
+        options: --cap-add SYS_PTRACE --name azuresqledge
         env:
           ACCEPT_EULA: Y
-          MSSQL_SA_PASSWORD: veryStrong123
+          MSSQL_SA_PASSWORD: "veryStrong123"
         ports:
           - 1433:1433
 
@@ -53,12 +54,9 @@ jobs:
         run: |
           for i in {1..10}; do
             sleep $((11 - i))
-            if echo "SELECT 1" | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P veryStrong123 &> /dev/null; then
-              echo "MSSQL is ready!"
-              break
-            fi
-            echo "Waiting for MSSQL to be ready..."
+            nc -z localhost 1435 && echo "Azure SQL Edge is ready" && exit 0
           done
+          echo "Azure SQL Edge failed to start" && exit 1
 
       - name: Run Tests with MSSQL
         run: mvn test -pl core -am -Dspring.profiles.active=mssql
